{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 38,
   "id": "9614f09b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[['Sunny', 'Warm', 'Normal', 'Strong', 'Warm', 'Same', 'Yes'], ['Sunny', 'Warm', 'High', 'Strong', 'Warm', 'Same', 'Yes'], ['Rainy', 'Cold', 'High', 'Strong', 'Warm', 'Change', 'No'], ['Sunny', 'Warm', 'High', 'Strong', 'Cool', 'Change', 'Yes']]\n",
      "['Sunny', 'Warm', 'Normal', 'Strong', 'Warm', 'Same']\n",
      "[['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]\n",
      "Step  1\n",
      "['Sunny', 'Warm', 'Normal', 'Strong', 'Warm', 'Same']\n",
      "[['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]\n",
      "Step  2\n",
      "['Sunny', 'Warm', '?', 'Strong', 'Warm', 'Same']\n",
      "[['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]\n",
      "Step  3\n",
      "['Sunny', 'Warm', '?', 'Strong', 'Warm', 'Same']\n",
      "[['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', 'Same']]\n",
      "Step  4\n",
      "['Sunny', 'Warm', '?', 'Strong', '?', '?']\n",
      "[['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]\n",
      "final specific hyp ['Sunny', 'Warm', '?', 'Strong', '?', '?']\n",
      "final general hypothesis [['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?']]\n"
     ]
    }
   ],
   "source": [
    "import csv\n",
    "with open('exp3.csv') as f:\n",
    "    csv_file=csv.reader(f)\n",
    "    data=list(csv_file)\n",
    "    print(data)\n",
    "    \n",
    "    sp=data[0][:-1]\n",
    "    ge=[['?' for i in range(len(sp))] for i in range(len(sp))]\n",
    "    \n",
    "    print(sp)\n",
    "    print(ge)\n",
    "    \n",
    "    count=1\n",
    "    for i in data:\n",
    "        if i[-1]=='Yes':\n",
    "            for j in range(len(sp)):\n",
    "                if i[j]!=sp[j]:\n",
    "                    sp[j]='?'\n",
    "                    ge[j][j] = \"?\"\n",
    "                    \n",
    "        elif i[-1]=='No':\n",
    "            for j in range(len(sp)):\n",
    "                if i[j]!=sp[j]:\n",
    "                    ge[j][j]=sp[j]\n",
    "                else:\n",
    "                    ge[j][j]=\"?\"\n",
    "                    \n",
    "        print('Step ',count)\n",
    "        count+=1\n",
    "        print(sp)\n",
    "        print(ge)\n",
    "        \n",
    "    gh=[]\n",
    "    for i in ge:\n",
    "        for j in i:\n",
    "            if j!='?':\n",
    "                gh.append(i)\n",
    "          \n",
    "    print('final specific hyp',sp)\n",
    "    print('final general hypothesis',gh)\n",
    "    \n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "id": "6308647c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[['Sunny', 'Warm', 'Normal', 'Strong', 'Warm', 'Same', 'Yes'], ['Sunny', 'Warm', 'High', 'Strong', 'Warm', 'Same', 'Yes'], ['Rainy', 'Cold', 'High', 'Strong', 'Warm', 'Change', 'No'], ['Sunny', 'Warm', 'High', 'Strong', 'Cool', 'Change', 'Yes']]\n",
      "['Sunny', 'Warm', 'Normal', 'Strong', 'Warm', 'Same']\n",
      "[['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]\n",
      "Step:  1\n",
      "['Sunny', 'Warm', 'Normal', 'Strong', 'Warm', 'Same']\n",
      "[['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]\n",
      "Step:  2\n",
      "['Sunny', 'Warm', '?', 'Strong', 'Warm', 'Same']\n",
      "[['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]\n",
      "Step:  3\n",
      "['Sunny', 'Warm', '?', 'Strong', 'Warm', 'Same']\n",
      "[['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', 'Same']]\n",
      "Step:  4\n",
      "['Sunny', 'Warm', '?', 'Strong', '?', '?']\n",
      "[['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]\n",
      "final sp hyp:  ['Sunny', 'Warm', '?', 'Strong', '?', '?']\n",
      "final ge hyp:  [['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?']]\n"
     ]
    }
   ],
   "source": [
    "import csv\n",
    "\n",
    "with open('exp3.csv') as f:\n",
    "    csv_file=csv.reader(f)\n",
    "    data=list(csv_file)\n",
    "    print(data)\n",
    "    \n",
    "    sp=data[0][:-1]\n",
    "    ge=[['?' for j in range(len(sp))] for i in range(len(sp))]\n",
    "    print(sp)\n",
    "    print(ge)\n",
    "    \n",
    "    count=1\n",
    "    for i in data:\n",
    "        if i[-1]=='Yes':\n",
    "            for j in range(len(sp)):\n",
    "                if i[j]!=sp[j]:\n",
    "                    sp[j]='?'\n",
    "                    ge[j][j]='?'\n",
    "        elif i[-1]=='No':\n",
    "            for j in range(len(sp)):\n",
    "                if i[j]!=sp[j]:\n",
    "                    ge[j][j]=sp[j]\n",
    "                else:\n",
    "                    ge[j][j]='?'\n",
    "        \n",
    "        print('Step: ',count)\n",
    "        count+=1\n",
    "        print(sp)\n",
    "        print(ge)\n",
    "        \n",
    "gh=[]\n",
    "for i in ge:\n",
    "    for j in i:\n",
    "        if j!='?':\n",
    "            gh.append(i)\n",
    "\n",
    "print(\"final sp hyp: \",sp)\n",
    "print(\"final ge hyp: \",gh)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "id": "06643b0b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[['Sunny', 'Warm', 'Normal', 'Strong', 'Warm', 'Same', 'Yes'], ['Sunny', 'Warm', 'High', 'Strong', 'Warm', 'Same', 'Yes'], ['Rainy', 'Cold', 'High', 'Strong', 'Warm', 'Change', 'No'], ['Sunny', 'Warm', 'High', 'Strong', 'Cool', 'Change', 'Yes']]\n",
      "step 1\n",
      "specific:  ['Sunny', 'Warm', 'Normal', 'Strong', 'Warm', 'Same']\n",
      "general:  [['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]\n",
      "step 2\n",
      "specific:  ['Sunny', 'Warm', '?', 'Strong', 'Warm', 'Same']\n",
      "general:  [['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]\n",
      "step 3\n",
      "specific:  ['Sunny', 'Warm', '?', 'Strong', 'Warm', 'Same']\n",
      "general:  [['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', 'Same']]\n",
      "step 4\n",
      "specific:  ['Sunny', 'Warm', '?', 'Strong', '?', '?']\n",
      "general:  [['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]\n",
      "final specific hypothesis:  ['Sunny', 'Warm', '?', 'Strong', '?', '?']\n",
      "Final general hypothesis:  [['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?']]\n"
     ]
    }
   ],
   "source": [
    "import csv\n",
    "\n",
    "with open('exp3.csv') as f:\n",
    "    csv_file=csv.reader(f)\n",
    "    data=list(csv_file)\n",
    "    \n",
    "    print(data)\n",
    "    sp=data[0][:-1]\n",
    "    ge=[['?' for j in range(len(sp))] for j in range(len(sp))]\n",
    "    \n",
    "    count=1\n",
    "    for i in data:\n",
    "        if i[-1]=='Yes':\n",
    "            for j in range(len(sp)):\n",
    "                if i[j]!=sp[j]:\n",
    "                    sp[j]='?'\n",
    "                    ge[j][j]='?'\n",
    "        \n",
    "        elif i[-1]=='No':\n",
    "            for j in range(len(sp)):\n",
    "                if i[j]!=sp[j]:\n",
    "                    ge[j][j]=sp[j]\n",
    "                else:\n",
    "                    ge[j][j]='?'\n",
    "                    \n",
    "        print('step',count)\n",
    "        print('specific: ',sp)\n",
    "        print('general: ',ge)\n",
    "        count+=1\n",
    "                    \n",
    "    gh=[]\n",
    "    \n",
    "    for i in ge:\n",
    "        for j in i:\n",
    "            if j!='?':\n",
    "                gh.append(i)\n",
    "                \n",
    "    print('final specific hypothesis: ',sp)\n",
    "    print('Final general hypothesis: ',gh)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "536f7a6e",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "78641f95",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "183b8471",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "08d120e2",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e7199cea",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2b2a3112",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1df5e082",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 42,
   "id": "811f2b53",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Step 1\n",
      "Specific:  ['Sunny', 'Warm', 'Normal', 'Strong', 'Warm', 'Same']\n",
      "General:  [['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]\n",
      "Step 2\n",
      "Specific:  ['Sunny', 'Warm', '?', 'Strong', 'Warm', 'Same']\n",
      "General:  [['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]\n",
      "Step 3\n",
      "Specific:  ['Sunny', 'Warm', '?', 'Strong', 'Warm', 'Same']\n",
      "General:  [['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', 'Same']]\n",
      "Step 4\n",
      "Specific:  ['Sunny', 'Warm', '?', 'Strong', '?', '?']\n",
      "General:  [['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]\n",
      "Final specific hypothesis:  ['Sunny', 'Warm', '?', 'Strong', '?', '?']\n",
      "Final general hypothesis:  [['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?']]\n"
     ]
    }
   ],
   "source": [
    "import csv\n",
    "\n",
    "with open('exp3.csv') as f:\n",
    "    csvf=csv.reader(f)\n",
    "    data=list(csvf)\n",
    "    \n",
    "    sp=data[0][:-1]\n",
    "    ge=[['?'  for j in range(len(sp))]  for j in range(len(sp))]\n",
    "    \n",
    "    count=1\n",
    "    for i in data:\n",
    "        if i[-1]=='Yes':\n",
    "            for j in range(len(sp)):\n",
    "                if i[j]!=sp[j]:\n",
    "                    sp[j]='?'\n",
    "                    ge[j][j]='?'\n",
    "                    \n",
    "        elif i[-1]=='No':\n",
    "            for j in range(len(sp)):\n",
    "                if i[j]!=sp[j]:\n",
    "                    ge[j][j]=sp[j]\n",
    "                else:\n",
    "                    ge[j][j]='?'\n",
    "                    \n",
    "        print('Step',count)\n",
    "        count+=1\n",
    "        print('Specific: ',sp)\n",
    "        print('General: ',ge)\n",
    "    \n",
    "    gh=[]\n",
    "    for i in ge:\n",
    "        for j in i:\n",
    "            if j!='?':\n",
    "                gh.append(i)\n",
    "                \n",
    "    print('Final specific hypothesis: ',sp)\n",
    "    print('Final general hypothesis: ',gh)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "75af2e25",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
