{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 39,
   "id": "837f21f4",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "featuress ['A1', 'A2', 'A3', 'classification']\n",
      "examples:        A1    A2      A3 classification\n",
      "0   True   Hot    High             No\n",
      "1   True   Hot    High             No\n",
      "2  False   Hot    High            Yes\n",
      "3  False  Cool  Normal            Yes\n",
      "4  False  Cool  Normal            Yes\n",
      "5   True  Cool    High             No\n",
      "6   True   Hot    High             No\n",
      "7   True   Hot  Normal            Yes\n",
      "8  False  Cool  Normal            Yes\n",
      "9  False  Cool    High             No\n",
      "\n",
      "uniq [False  True]\n",
      "\n",
      "subdata       A1    A2      A3 classification\n",
      "2  False   Hot    High            Yes\n",
      "3  False  Cool  Normal            Yes\n",
      "4  False  Cool  Normal            Yes\n",
      "8  False  Cool  Normal            Yes\n",
      "9  False  Cool    High             No\n",
      "\n",
      "subdata      A1    A2      A3 classification\n",
      "0  True   Hot    High             No\n",
      "1  True   Hot    High             No\n",
      "5  True  Cool    High             No\n",
      "6  True   Hot    High             No\n",
      "7  True   Hot  Normal            Yes\n",
      "examples:        A1    A2      A3 classification\n",
      "0   True   Hot    High             No\n",
      "1   True   Hot    High             No\n",
      "2  False   Hot    High            Yes\n",
      "3  False  Cool  Normal            Yes\n",
      "4  False  Cool  Normal            Yes\n",
      "5   True  Cool    High             No\n",
      "6   True   Hot    High             No\n",
      "7   True   Hot  Normal            Yes\n",
      "8  False  Cool  Normal            Yes\n",
      "9  False  Cool    High             No\n",
      "\n",
      "uniq ['Cool' 'Hot']\n",
      "\n",
      "subdata       A1    A2      A3 classification\n",
      "3  False  Cool  Normal            Yes\n",
      "4  False  Cool  Normal            Yes\n",
      "5   True  Cool    High             No\n",
      "8  False  Cool  Normal            Yes\n",
      "9  False  Cool    High             No\n",
      "\n",
      "subdata       A1   A2      A3 classification\n",
      "0   True  Hot    High             No\n",
      "1   True  Hot    High             No\n",
      "2  False  Hot    High            Yes\n",
      "6   True  Hot    High             No\n",
      "7   True  Hot  Normal            Yes\n",
      "examples:        A1    A2      A3 classification\n",
      "0   True   Hot    High             No\n",
      "1   True   Hot    High             No\n",
      "2  False   Hot    High            Yes\n",
      "3  False  Cool  Normal            Yes\n",
      "4  False  Cool  Normal            Yes\n",
      "5   True  Cool    High             No\n",
      "6   True   Hot    High             No\n",
      "7   True   Hot  Normal            Yes\n",
      "8  False  Cool  Normal            Yes\n",
      "9  False  Cool    High             No\n",
      "\n",
      "uniq ['High' 'Normal']\n",
      "\n",
      "subdata       A1    A2    A3 classification\n",
      "0   True   Hot  High             No\n",
      "1   True   Hot  High             No\n",
      "2  False   Hot  High            Yes\n",
      "5   True  Cool  High             No\n",
      "6   True   Hot  High             No\n",
      "9  False  Cool  High             No\n",
      "\n",
      "subdata       A1    A2      A3 classification\n",
      "3  False  Cool  Normal            Yes\n",
      "4  False  Cool  Normal            Yes\n",
      "7   True   Hot  Normal            Yes\n",
      "8  False  Cool  Normal            Yes\n",
      "examples:        A1    A2    A3 classification\n",
      "0   True   Hot  High             No\n",
      "1   True   Hot  High             No\n",
      "2  False   Hot  High            Yes\n",
      "5   True  Cool  High             No\n",
      "6   True   Hot  High             No\n",
      "9  False  Cool  High             No\n",
      "\n",
      "uniq [False  True]\n",
      "\n",
      "subdata       A1    A2    A3 classification\n",
      "2  False   Hot  High            Yes\n",
      "9  False  Cool  High             No\n",
      "\n",
      "subdata      A1    A2    A3 classification\n",
      "0  True   Hot  High             No\n",
      "1  True   Hot  High             No\n",
      "5  True  Cool  High             No\n",
      "6  True   Hot  High             No\n",
      "examples:        A1    A2    A3 classification\n",
      "0   True   Hot  High             No\n",
      "1   True   Hot  High             No\n",
      "2  False   Hot  High            Yes\n",
      "5   True  Cool  High             No\n",
      "6   True   Hot  High             No\n",
      "9  False  Cool  High             No\n",
      "\n",
      "uniq ['Cool' 'Hot']\n",
      "\n",
      "subdata       A1    A2    A3 classification\n",
      "5   True  Cool  High             No\n",
      "9  False  Cool  High             No\n",
      "\n",
      "subdata       A1   A2    A3 classification\n",
      "0   True  Hot  High             No\n",
      "1   True  Hot  High             No\n",
      "2  False  Hot  High            Yes\n",
      "6   True  Hot  High             No\n",
      "examples:        A1    A2    A3 classification\n",
      "2  False   Hot  High            Yes\n",
      "9  False  Cool  High             No\n",
      "\n",
      "uniq ['Cool' 'Hot']\n",
      "\n",
      "subdata       A1    A2    A3 classification\n",
      "9  False  Cool  High             No\n",
      "\n",
      "subdata       A1   A2    A3 classification\n",
      "2  False  Hot  High            Yes\n",
      "A3\n",
      "\tHigh\n",
      "\t\tA1\n",
      "\t\t\tFalse\n",
      "\t\t\t\tA2\n",
      "\t\t\t\t\tCool ->  ['No']\n",
      "\n",
      "\t\t\t\t\tHot ->  ['Yes']\n",
      "\n",
      "\t\t\tTrue ->  ['No']\n",
      "\n",
      "\tNormal ->  ['Yes']\n",
      "\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import math\n",
    "import numpy as np\n",
    "\n",
    "data = pd.read_csv(\"exp4.csv\")\n",
    "features = [feat for feat in data]\n",
    "print('featuress',features)\n",
    "features.remove(\"classification\")\n",
    "\n",
    "class Node:\n",
    "    def __init__(self):\n",
    "        self.children = []\n",
    "        self.value = \"\"\n",
    "        self.isLeaf = False\n",
    "        self.pred = \"\"\n",
    "\n",
    "def entropy(examples):\n",
    "    pos = 0.0\n",
    "    neg = 0.0\n",
    "#     print('examples: ',examples)\n",
    "    for _, row in examples.iterrows():\n",
    "#         print('row: ',row)\n",
    "        if row[\"classification\"] == \"Yes\":\n",
    "            pos += 1\n",
    "        else:\n",
    "            neg += 1\n",
    "    if pos == 0.0 or neg == 0.0:\n",
    "        return 0.0\n",
    "    else:\n",
    "        p = pos / (pos + neg)\n",
    "        n = neg / (pos + neg)\n",
    "        return -(p * math.log(p, 2) + n * math.log(n, 2))\n",
    "\n",
    "def info_gain(examples, attr):\n",
    "    print('examples: ',examples)\n",
    "    uniq = np.unique(examples[attr])\n",
    "    print (\"\\nuniq\",uniq)\n",
    "    gain = entropy(examples)\n",
    "#     print (\"\\ngain\",gain)\n",
    "    for u in uniq:\n",
    "        subdata = examples[examples[attr] == u]\n",
    "        print (\"\\nsubdata\",subdata)\n",
    "        sub_e = entropy(subdata)\n",
    "        gain -= (float(len(subdata)) / float(len(examples))) * sub_e\n",
    "        #print (\"\\n\",gain)\n",
    "    return gain\n",
    "\n",
    "def ID3(examples, attrs):\n",
    "    root = Node()\n",
    "\n",
    "    max_gain = 0\n",
    "    max_feat = \"\"\n",
    "    for feature in attrs:\n",
    "        #print (\"\\n\",examples)\n",
    "        gain = info_gain(examples, feature)\n",
    "        if gain > max_gain:\n",
    "            max_gain = gain\n",
    "            max_feat = feature\n",
    "    root.value = max_feat\n",
    "    #print (\"\\nMax feature attr\",max_feat)\n",
    "    uniq = np.unique(examples[max_feat])\n",
    "    #print (\"\\n\",uniq)\n",
    "    for u in uniq:\n",
    "        #print (\"\\n\",u)\n",
    "        subdata = examples[examples[max_feat] == u]\n",
    "        #print (\"\\n\",subdata)\n",
    "        if entropy(subdata) == 0.0:\n",
    "            newNode = Node()\n",
    "            newNode.isLeaf = True\n",
    "            newNode.value = u\n",
    "            newNode.pred = np.unique(subdata[\"classification\"])\n",
    "            root.children.append(newNode)\n",
    "        else:\n",
    "            dummyNode = Node()\n",
    "            dummyNode.value = u\n",
    "            new_attrs = attrs.copy()\n",
    "            new_attrs.remove(max_feat)\n",
    "            child = ID3(subdata, new_attrs)\n",
    "            dummyNode.children.append(child)\n",
    "            root.children.append(dummyNode)\n",
    "    return root\n",
    "\n",
    "def printTree(root: Node, depth=0):\n",
    "    for i in range(depth):\n",
    "        print(\"\\t\", end=\"\")\n",
    "    print(root.value, end=\"\")\n",
    "    if root.isLeaf:\n",
    "        print(\" -> \", root.pred)\n",
    "    print()\n",
    "    for child in root.children:\n",
    "        printTree(child, depth + 1)\n",
    "\n",
    "root = ID3(data, features)\n",
    "printTree(root)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 72,
   "id": "265b611b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['A1', 'A2', 'A3']\n",
      "A3\n",
      "\tHigh\n",
      "\t\tA1\n",
      "\t\t\tFalse\n",
      "\t\t\t\tA2\n",
      "\t\t\t\t\tCool-> ['No']\n",
      "\n",
      "\t\t\t\t\tHot-> ['Yes']\n",
      "\n",
      "\t\t\tTrue-> ['No']\n",
      "\n",
      "\tNormal-> ['Yes']\n",
      "\n"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "import math\n",
    "import pandas as pd\n",
    "\n",
    "data=pd.read_csv('exp4.csv')\n",
    "feature=[feat for feat in data]\n",
    "feature.remove(\"classification\")\n",
    "print(feature)\n",
    "\n",
    "class Node:\n",
    "    def __init__(self):\n",
    "        self.child=[]\n",
    "        self.value=\"\"\n",
    "        self.leaf=False\n",
    "        self.pred=\"\"\n",
    "        \n",
    "def entropy(exam):\n",
    "    pos=0.0\n",
    "    neg=0.0\n",
    "    for _,row in exam.iterrows():\n",
    "        if row[\"classification\"]==\"Yes\":\n",
    "            pos+=1\n",
    "        else:\n",
    "            neg+=1\n",
    "    if pos==0 or neg==0:\n",
    "        return 0.0\n",
    "    p=pos/(pos+neg)\n",
    "    n=neg/(pos+neg)\n",
    "    return -(p * math.log(p, 2) + n * math.log(n, 2))\n",
    "\n",
    "def ig(exam,attr):\n",
    "    uniq=np.unique(exam[attr])\n",
    "    g=entropy(exam)\n",
    "    for u in uniq:\n",
    "        sd=exam[exam[attr]==u]\n",
    "        se=entropy(sd)\n",
    "        g-=(float(len(sd))/float(len(exam)))*se\n",
    "    return g\n",
    "\n",
    "def id3(exam,attr):\n",
    "    root=Node()\n",
    "    mf=\"\"\n",
    "    mg=0\n",
    "    \n",
    "    for f in attr:\n",
    "        g=ig(exam,f)\n",
    "        if g>mg:\n",
    "            mg=g\n",
    "            mf=f\n",
    "            \n",
    "    root.value=mf\n",
    "    \n",
    "    uniq=np.unique(exam[mf])\n",
    "    for u in uniq:\n",
    "        sd=exam[exam[mf]==u]\n",
    "        if entropy(sd)==0:\n",
    "            n=Node()\n",
    "            n.value=u\n",
    "            n.leaf=True\n",
    "            n.pred=np.unique(sd[\"classification\"])\n",
    "            root.child.append(n)\n",
    "            \n",
    "        else:\n",
    "            d=Node()\n",
    "            d.value=u\n",
    "            na=attr.copy()\n",
    "            na.remove(mf)\n",
    "            c=id3(sd,na)\n",
    "            d.child.append(c)\n",
    "            root.child.append(d)\n",
    "            \n",
    "    return root\n",
    "\n",
    "def pt(root:Node(),d=0):\n",
    "    for i in range(d):\n",
    "        print(\"\\t\",end=\"\")\n",
    "    print(root.value,end=\"\")\n",
    "    if root.leaf:\n",
    "        print(\"->\",root.pred)\n",
    "    print()\n",
    "    for c in root.child:\n",
    "        pt(c,d+1)\n",
    "    \n",
    "root=id3(data,feature)\n",
    "pt(root)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "149796c3",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "823d5877",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a50c005b",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c1748ea5",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b22c9e4e",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ac148b7e",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 73,
   "id": "1786ddea",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['A1', 'A2', 'A3']\n",
      "A3\n",
      "\tHigh\n",
      "\t\tA1\n",
      "\t\t\tFalse\n",
      "\t\t\t\tA2\n",
      "\t\t\t\t\tCool-> ['No']\n",
      "\n",
      "\t\t\t\t\tHot-> ['Yes']\n",
      "\n",
      "\t\t\tTrue-> ['No']\n",
      "\n",
      "\tNormal-> ['Yes']\n",
      "\n"
     ]
    }
   ],
   "source": [
    "import math\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "\n",
    "data=pd.read_csv('exp4.csv')\n",
    "feature=[feat for feat in data]\n",
    "feature.remove(\"classification\")\n",
    "print(feature)\n",
    "\n",
    "class Node:\n",
    "    def __init__(self):\n",
    "        self.child=[]\n",
    "        self.value=\"\"\n",
    "        self.leaf=False\n",
    "        self.pred=\"\"\n",
    "    \n",
    "def entropy(exam):\n",
    "    pos=0.0\n",
    "    neg=0.0\n",
    "    for _,row in exam.iterrows():\n",
    "        if row[\"classification\"]==\"Yes\":\n",
    "            pos+=1\n",
    "        else:\n",
    "            neg+=1\n",
    "    if pos==0 or neg==0:\n",
    "        return 0.0\n",
    "    p=pos/(pos+neg)\n",
    "    n=neg/(pos+neg)\n",
    "    return -(p * math.log(p, 2) + n * math.log(n, 2))\n",
    "        \n",
    "def ig(exam,attr):\n",
    "    uniq=np.unique(exam[attr])\n",
    "    g=entropy(exam)\n",
    "    for u in uniq:\n",
    "        sd=exam[exam[attr]==u]\n",
    "        se=entropy(sd)\n",
    "        g-=(float(len(sd))/float(len(exam)))*se\n",
    "    return g\n",
    "\n",
    "def id3(exam,attr):\n",
    "    root=Node()\n",
    "    mf=\"\"\n",
    "    mg=0\n",
    "    \n",
    "    for f in attr:\n",
    "        g=ig(exam,f)\n",
    "        if g>mg:\n",
    "            mg=g\n",
    "            mf=f\n",
    "            \n",
    "    root.value=mf\n",
    "    \n",
    "    uniq=np.unique(exam[mf])\n",
    "    for u in uniq:\n",
    "        sd=exam[exam[mf]==u]\n",
    "        if entropy(sd)==0:\n",
    "            n=Node()\n",
    "            n.value=u\n",
    "            n.leaf=True\n",
    "            n.pred=np.unique(sd[\"classification\"])\n",
    "            root.child.append(n)\n",
    "            \n",
    "        else:\n",
    "            d=Node()\n",
    "            d.value=u\n",
    "            na=attr.copy()\n",
    "            na.remove(mf)\n",
    "            c=id3(sd,na)\n",
    "            d.child.append(c)\n",
    "            root.child.append(d)\n",
    "            \n",
    "    return root\n",
    "\n",
    "def pt(root:Node(),d=0):\n",
    "    for i in range(d):\n",
    "        print(\"\\t\",end=\"\")\n",
    "    print(root.value,end=\"\")\n",
    "    if root.leaf:\n",
    "        print(\"->\",root.pred)\n",
    "    print()\n",
    "    for c in root.child:\n",
    "        pt(c,d+1)\n",
    "\n",
    "root=id3(data,feature)\n",
    "pt(root)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1624c28c",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7be31821",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1404a871",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "88e82acf",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "de1fe055",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "726b1a9a",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 92,
   "id": "b04cd748",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "A3\n",
      "\tHigh\n",
      "\t\tA1\n",
      "\t\t\tFalse\n",
      "\t\t\t\tA2\n",
      "\t\t\t\t\tCool-> ['No']\n",
      "\n",
      "\t\t\t\t\tHot-> ['Yes']\n",
      "\n",
      "\t\t\tTrue-> ['No']\n",
      "\n",
      "\tNormal-> ['Yes']\n",
      "\n"
     ]
    }
   ],
   "source": [
    "import math\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "\n",
    "data=pd.read_csv('exp4.csv')\n",
    "feature=[feat for feat in data]\n",
    "feature.remove(\"classification\")\n",
    "\n",
    "class Node:\n",
    "    def __init__(self):\n",
    "        self.child=[]\n",
    "        self.value=\"\"\n",
    "        self.leaf=False\n",
    "        self.pred=\"\"\n",
    "        \n",
    "def e(exam):\n",
    "    pos=0.0\n",
    "    neg=0.0\n",
    "    for _,row in exam.iterrows():\n",
    "        if row[\"classification\"]==\"Yes\":\n",
    "            pos+=1\n",
    "        else:\n",
    "            neg+=1\n",
    "    if pos==0.0 or neg==0.0:\n",
    "        return 0\n",
    "    p=pos/(pos+neg)\n",
    "    n=neg/(pos+neg)\n",
    "    return -(p*math.log(p,2)+n*math.log(n,2))\n",
    "\n",
    "def ig(exam,attr):\n",
    "    g=e(exam)\n",
    "    uniq=np.unique(exam[attr])\n",
    "    for u in uniq:\n",
    "        sd=exam[exam[attr]==u]\n",
    "        se=e(sd)\n",
    "        g-=(float(len(sd))/float(len(exam)))*se\n",
    "    return g\n",
    "\n",
    "def id3(exam,attr):\n",
    "    root=Node()\n",
    "    mf=\"\"\n",
    "    mg=0\n",
    "    \n",
    "    for f in attr:\n",
    "        g=ig(exam,f)\n",
    "        if g>mg:\n",
    "            mg=g\n",
    "            mf=f\n",
    "            \n",
    "    root.value=mf\n",
    "    \n",
    "    uniq=np.unique(exam[mf])\n",
    "    for u in uniq:\n",
    "        sd=exam[exam[mf]==u]\n",
    "        if e(sd)==0:\n",
    "            n=Node()\n",
    "            n.leaf=True\n",
    "            n.value=u\n",
    "            n.pred=np.unique(sd[\"classification\"])\n",
    "            root.child.append(n)\n",
    "            \n",
    "        else:\n",
    "            d=Node()\n",
    "            d.value=u\n",
    "            na=attr.copy()\n",
    "            na.remove(mf)\n",
    "            c=id3(sd,na)\n",
    "            d.child.append(c)\n",
    "            root.child.append(d)\n",
    "            \n",
    "    return root\n",
    "\n",
    "def pt(root:Node(),d=0):\n",
    "    for i in range(d):\n",
    "        print(\"\\t\",end=\"\")\n",
    "    print(root.value,end=\"\")\n",
    "    if root.leaf:\n",
    "        print(\"->\",root.pred)\n",
    "    print()\n",
    "    for c in root.child:\n",
    "        pt(c,d+1)\n",
    "        \n",
    "root=id3(data,feature)\n",
    "pt(root)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7fe90c61",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
